export const SET_USERNAME: string = 'SET_USERNAME';

export const GET_ALL_COINS_LOADING = 'GET_ALL_COINS_LOADING';
export const GET_ALL_COINS_SUCCESS = 'GET_ALL_COINS_SUCCESS';
export const GET_ALL_COINS_ERROR = 'GET_ALL_COINS_ERROR';

export const GET_COIN_BY_ID_LOADING = 'GET_COIN_BY_ID_LOADING';
export const GET_COIN_BY_ID_SUCCESS = 'GET_COIN_BY_ID_SUCCESS';
export const GET_COIN_BY_ID_ERROR = 'GET_COIN_BY_ID_ERROR';

export const SET_CURRENT_COIN = 'SET_CURRENT_COIN';

export const SET_DEVICE_CONNECTION = 'SET_DEVICE_CONNECTION';
